services:
  mysql:
    image: mysql:8.4
    container_name: msusers-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT:-3306}:3306'
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - msusers_mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-p${DB_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: msusers-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: msusers-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Default: 'server=mysql;port=3306;database=${DB_NAME};user=${DB_USER};password=${DB_PASSWORD};TreatTinyAsBoolean=false'
      # Puedes agregar más variables aquí si lo necesitas
    ports:
      - '${API_HOST_PORT:-8080}:8080'

volumes:
  msusers_mysql:
# Para usar un archivo de entorno específico:
#   docker compose --env-file .env.development up
#   docker compose --env-file .env.production up
