services:
  mysql:
    image: mysql:8.4
    container_name: msusers-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-aF3MK0ZuWMHHXyX1ZwWjmKoS4baBAUgL}
      MYSQL_DATABASE: ${DB_NAME:-usersdb}
      MYSQL_USER: ${DB_USER:-msuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-UsrApp2025SecurePass}
    ports:
      - '${DB_PORT:-3307}:3306'
    volumes:
      - msusers_mysql:/var/lib/mysql
      - ./init-users-db.sql:/docker-entrypoint-initdb.d/01-init-users.sql:ro
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-p${DB_ROOT_PASSWORD:-aF3MK0ZuWMHHXyX1ZwWjmKoS4baBAUgL}',
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: msusers-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: msusers-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ConnectionStrings__Default: 'server=mysql;port=3306;database=${DB_NAME:-usersdb};user=${DB_USER:-msuser};password=${DB_PASSWORD:-UsrApp2025SecurePass};TreatTinyAsBoolean=false'
    ports:
      - '${API_HOST_PORT:-8081}:8081'

volumes:
  msusers_mysql:
# Para usar un archivo de entorno espec√≠fico:
#   docker compose --env-file .env.development up
#   docker compose --env-file .env.production up
